### PR TITLE
Performance fix

### PR DESCRIPTION
**Pull request by iSentrie**
Haven't tested this, but this is what I would do for such concept.

### CODE REVIEW

**Comment by Musiker15** [comment]
Your changes won't work.

**Comment by iSentrie** [comment]
Why not?

**Comment by Musiker15** [comment]
Because you have to do `local playerPed = PlayerPedId()` in every `while loop`. You forgot it in the last one. Otherwise `local playerPed = PlayerPedId()` or only `PlayerPedId()` is just the same.

**Comment by iSentrie** [comment]
I declared `local playerPed = PlayerPedId()` for whole script, so you might be wrong.

**Pull request closed without merging**
